# Generated by Django 4.2.4 on 2023-08-07 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myineffable', '0002_centreregisteradmin_centerdatetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentreRegisterStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255)),
                ('mother_name', models.CharField(max_length=255)),
                ('father_name', models.CharField(max_length=255)),
                ('rollno', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=255)),
                ('Dob', models.CharField(max_length=255)),
                ('centre_name', models.CharField(max_length=255)),
                ('course_name', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=255)),
                ('examheldon', models.CharField(max_length=255)),
                ('percent', models.CharField(max_length=255)),
                ('grade', models.CharField(max_length=255)),
                ('session', models.CharField(max_length=255)),
                ('centre_code', models.CharField(max_length=255)),
                ('dateofissue', models.CharField(max_length=255)),
                ('remark', models.CharField(max_length=255)),
                ('mark_s1', models.CharField(max_length=255)),
                ('mark_s2', models.CharField(max_length=255)),
                ('mark_s3', models.CharField(max_length=255)),
                ('mark_s4', models.CharField(max_length=255)),
                ('mark_s5', models.CharField(max_length=255)),
                ('written_mark', models.CharField(max_length=255)),
                ('practical_mark', models.CharField(max_length=255)),
                ('assignment_mark', models.CharField(max_length=255)),
                ('viva_mark', models.CharField(max_length=255)),
            ],
        ),
    ]
