# Generated by Django 4.2.4 on 2023-08-10 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myineffable', '0005_centreregisterstudent_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='centreregisteradmin',
            name='center_password',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
