# Generated by Django 4.2.4 on 2023-08-15 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myineffable', '0007_centreregisterstudent_upload_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='centreregisterstudent',
            name='id',
        ),
        migrations.AlterField(
            model_name='centreregisterstudent',
            name='rollno',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
