# Generated by Django 4.2.4 on 2023-08-20 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myineffable', '0008_remove_centreregisterstudent_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='centreregisteradmin',
            name='owner_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
